# Generated by Django 5.2.5 on 2025-09-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серійний номер групи')),
                ('name', models.CharField(max_length=100, verbose_name='Назва групи')),
            ],
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серійний номер підсистеми')),
                ('system', models.CharField(blank=True, max_length=100, verbose_name='Система')),
                ('subsystem', models.CharField(blank=True, max_length=100, verbose_name='Підсистема')),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='imagApp.maingroup')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серійний номер')),
                ('name', models.CharField(max_length=100, verbose_name='Виріб')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (євро)')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Виробник')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('supplier_contact', models.TextField(blank=True, null=True, verbose_name='Контактна особа постачальника')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imagApp.subsystem')),
            ],
        ),
    ]
