# Generated by Django 5.2.5 on 2025-09-04 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серійний номер групи')),
                ('name', models.CharField(max_length=100, verbose_name='Назва групи')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (євро)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серійний номер')),
                ('name', models.CharField(max_length=100, verbose_name='Виріб')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (євро)')),
                ('stock', models.IntegerField(verbose_name='Кількість')),
                ('description', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120, verbose_name='Виробник')),
                ('model', models.CharField(blank=True, default='', max_length=120, verbose_name='Модель')),
                ('supplier_contact', models.CharField(blank=True, max_length=120, verbose_name='Контактна особа постачальника')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='imagApp.productgroup')),
            ],
        ),
    ]
