# Generated by Django 5.2.5 on 2025-09-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серійний номер')),
                ('name', models.CharField(max_length=100, verbose_name='Виріб')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (євро)')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Виробник')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('supplier_contact', models.TextField(blank=True, null=True, verbose_name='Контактна особа постачальника')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='imagApp.subsystem')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
