# Generated by Django 5.2.5 on 2025-08-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=120, verbose_name='Виробник'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_contact_person',
            field=models.CharField(blank=True, max_length=120, verbose_name='Контактна особа постачальника'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_site',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Виріб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (євро)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Кількість'),
        ),
    ]
