# Generated by Django 5.2.5 on 2025-08-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagApp', '0002_product_description_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_site',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_tel',
        ),
    ]
