# Generated by Django 5.2.5 on 2025-08-29 20:37
from django.db import migrations

def fill_serial_numbers(apps, schema_editor):
    Product = apps.get_model('imagApp', 'Product')
    for obj in Product.objects.all():
        if not obj.serial_number:
            obj.serial_number = f"S{obj.pk:07d}"  # приклад автонумерації для існуючих
            obj.save(update_fields=['serial_number'])

class Migration(migrations.Migration):

    dependencies = [
        ('imagApp', '0004_product_serial_number_product_supplier_email_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_serial_numbers, migrations.RunPython.noop),
    ]
