# Generated by Django 5.2.5 on 2025-08-29 20:42
from django.db import migrations, models

def backfill_serial_numbers(apps, schema_editor):
    Product = apps.get_model('imagApp', 'Product')
    for obj in Product.objects.all():
        sn = (obj.serial_number or "").strip()
        if not sn:
            # гарантовано унікально (прив'язано до pk)
            obj.serial_number = f"S{obj.pk:07d}"
            obj.save(update_fields=['serial_number'])

class Migration(migrations.Migration):

    dependencies = [
        ('imagApp', '0005_fill_serial_numbers'),
    ]

    operations = [
        migrations.RunPython(backfill_serial_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Серійний номер'),
        ),
    ]