# Generated by Django 5.2.5 on 2025-08-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagApp', '0006_alter_product_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_contact_person',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_site',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_tel',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=120, verbose_name='Контактна особа постачальника'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Виріб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (євро)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Кількість'),
        ),
    ]
